ALTER TABLE DEPART
RENAME TO DEPARTS;

ALTER TABLE EMPLE
RENAME TO EMPLEADOS;


CREATE TABLE PRESUPUESTOS(
	DEPT_NO NUMBER	(4) NOT NULL,
	ANIO NUMBER(4) NOT NULL,
	IMPORTE NUMBER (10,2),
		
	CONSTRAINT PK_PRESUPUESTOS PRIMARY KEY (ANIO,DEPT_NO),
	CONSTRAINT FK_PRESUPUSTOS_DEPARTS FOREIGN KEY (DEPT_NO) REFERENCES DEPARTS(DEPT_NO),
	CONSTRAINT CK_IMPORTE CHECK (IMPORTE>0)
);
--En la creacion de presupuestos habra que hacerlo con el año actual de la insercion


-- Tabla EMPLEADOS
ALTER TABLE EMPLEADOS
ALTER COLUMN EMP_NO NUMBER(4) NOT NULL,
ALTER COLUMN APELLIDO VARCHAR2(10) NOT NULL,
ADD CONSTRAINT CK_SALARIO CHECK (SALARIO>1221);

UPDATE EMPLEADOS SET SALARIO = (SALARIO / 166.386, 2),
                    COMISION = (NVL(COMISION, 0) / 166.386, 2);
					
					
-- Tabla TESOREROS
CREATE TABLE TESOREROS(
    EMP_NO NUMBER(4) NOT NULL,
    DEPT_NO NUMBER(2) NOT NULL,
    CONSTRAINT PK_TESOREROS PRIMARY KEY (EMP_NO),
    CONSTRAINT FK_TESOREROS_EMPLEADOS FOREIGN KEY (EMP_NO) REFERENCES EMPLEADOS (EMP_NO)
	--CONSTRAINT FK_TESOREROS_EMPLEADOS FOREIGN KEY (DEPT_NO) REFERENCES DEPARTS (DEPT_NO)
	
);

--Por cada adicion en esta tabla habra que comprobar que no este en coordinadores y borrar de la otra
 

-- Tabla COORDINADORES
CREATE TABLE COORDINADORES(
    EMP_NO NUMBER(4) NOT NULL,
    DEPT_NO NUMBER(2) NOT NULL UNIQUE,
    CONSTRAINT PK_COORD_EMPLE PRIMARY KEY (EMP_NO),
    CONSTRAINT FK_COORD_DEPART FOREIGN KEY (DEPT_NO) REFERENCES DEPART (DEPT_NO)
	--CONSTRAINT FK_COORDINADORES_EMPLEADOS FOREIGN KEY (EMP_NO) REFERENCES EMPLEADOS (EMP_NO)
	
	
)




	
	
