ALTER TABLE DEPART RENAME TO DEPARTS;
ALTER TABLE EMPLE RENAME TO EMPLEADOS;

CREATE TABLE PRESUPUESTOS(
	DEPT_NO NUMBER(4) NOT NULL,
	ANIO NUMBER(4) NOT NULL,
	IMPORTE NUMBER(10,2),
	CONSTRAINT PK_PRESUPUESTOS PRIMARY KEY (ANIO, DEPT_NO),
	CONSTRAINT FK_PRESUPUSTOS_DEPARTS FOREIGN KEY (DEPT_NO) REFERENCES DEPARTS(DEPT_NO),
	CONSTRAINT CK_IMPORTE CHECK (IMPORTE > 0)
);
--En la creacion de presupuestos habra que hacerlo con el año actual de la insercion


-- Tabla EMPLEADOS
ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_EMP_NO_NN CHECK (EMP_NO IS NOT NULL);
ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_APELLIDO_NN CHECK (APELLIDO IS NOT NULL);

ALTER TABLE EMPLEADOS ADD TIPO VARCHAR2(13);

ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_TIPO CHECK (TIPO IN ('COORDINADOR', 'TESORERO'));
ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_SALARIO CHECK (SALARIO > 1221);

UPDATE EMPLEADOS 
SET SALARIO = ROUND(SALARIO / 166.386, 2),
    COMISION = ROUND(NVL(COMISION, 0) / 166.386, 2);


UPDATE EMPLEADOS
SET TIPO='COORDINADOR'
WHERE EMP_NO = 7499;

UPDATE EMPLEADOS
SET TIPO='COORDINADOR'
WHERE EMP_NO =7782;

UPDATE EMPLEADOS
SET TIPO='TESORERO'
WHERE EMP_NO= 7521;

					

--Por cada adicion en esta tabla habra que comprobar que no este en coordinadores y borrar de la otra
 




	
	
