CREATE TABLE TESOREROS(
    EMP_NO NUMBER(4) NOT NULL,
    DEPT_NO NUMBER(2) NOT NULL,
    CONSTRAINT PK_TESOREROS PRIMARY KEY (EMP_NO),
    CONSTRAINT FK_TESOREROS_EMPLEADOS FOREIGN KEY (EMP_NO) REFERENCES DEPARTS
);


CREATE TABLE ES_DIRECTOR(
    EMP_NO NUMBER(4) NOT NULL,
    CONSTRAINT PK_ES_DIRECTOR PRIMARY KEY (EMP_NO),
    CONSTRAINT FK_ES_DIRECTOR_EMPLEADOS FOREIGN KEY (EMP_NO) REFERENCES EMPLE
);
